// <auto-generated />
using System;
using Dryadas.Models.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dryadas.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230628030833_nombre de la migra")]
    partial class nombredelamigra
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dryadas.Models.Data.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Agregado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreContrato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaginaWeb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PesoDeHuellaAmb")
                        .HasColumnType("real");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<string>("Segmento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.Property<int>("Telefono2")
                        .HasColumnType("int");

                    b.HasKey("IdCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Dryadas.Models.Data.DetalleEvento", b =>
                {
                    b.Property<int>("IdDetalleEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleEvento"));

                    b.Property<int>("IdEvento")
                        .HasColumnType("int");

                    b.Property<int>("IdOrden")
                        .HasColumnType("int");

                    b.HasKey("IdDetalleEvento");

                    b.HasIndex("IdEvento");

                    b.HasIndex("IdOrden");

                    b.ToTable("DetalleEventos");
                });

            modelBuilder.Entity("Dryadas.Models.Data.DetalleOrden", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("CantidadSinUsar")
                        .HasColumnType("int");

                    b.Property<int>("CantidadTotal")
                        .HasColumnType("int");

                    b.Property<int>("CantidadUsados")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFinal")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<int>("IdOrden")
                        .HasColumnType("int");

                    b.Property<int>("SKU")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("IdOrden");

                    b.HasIndex("SKU");

                    b.ToTable("DetalleOrdenes");
                });

            modelBuilder.Entity("Dryadas.Models.Data.Estado", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstado"));

                    b.Property<string>("NombreEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEstado");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("Dryadas.Models.Data.EstadoProducto", b =>
                {
                    b.Property<int>("IdEstadoProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoProducto"));

                    b.Property<string>("NombreEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEstadoProducto");

                    b.ToTable("EstadoProductos");
                });

            modelBuilder.Entity("Dryadas.Models.Data.EstadoProductoProducto", b =>
                {
                    b.Property<int>("IdEstadoProductoProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoProductoProducto"));

                    b.Property<int>("SKU")
                        .HasColumnType("int");

                    b.Property<int>("idEstadoProducto")
                        .HasColumnType("int");

                    b.HasKey("IdEstadoProductoProducto");

                    b.HasIndex("SKU");

                    b.HasIndex("idEstadoProducto");

                    b.ToTable("EstadoProductoProductos");
                });

            modelBuilder.Entity("Dryadas.Models.Data.EstadosOrden", b =>
                {
                    b.Property<int>("IdEstadosOrden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadosOrden"));

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int>("IdOrden")
                        .HasColumnType("int");

                    b.HasKey("IdEstadosOrden");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdOrden");

                    b.ToTable("EstadosOrdenes");
                });

            modelBuilder.Entity("Dryadas.Models.Data.Evento", b =>
                {
                    b.Property<int>("IdEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEvento"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEvento");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("Dryadas.Models.Data.Familia", b =>
                {
                    b.Property<int>("IdFamilia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFamilia"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdFamilia");

                    b.ToTable("Familias");
                });

            modelBuilder.Entity("Dryadas.Models.Data.Orden", b =>
                {
                    b.Property<int>("IdOrden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrden"));

                    b.Property<string>("Alquiler")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClienteIdCliente")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdOrden");

                    b.HasIndex("ClienteIdCliente");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("Dryadas.Models.Data.Privilegios", b =>
                {
                    b.Property<int>("IdPrivilegios")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrivilegios"));

                    b.HasKey("IdPrivilegios");

                    b.ToTable("Privilegios");
                });

            modelBuilder.Entity("Dryadas.Models.Data.Producto", b =>
                {
                    b.Property<int>("SKU")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SKU"));

                    b.Property<int>("AlquilerComercio")
                        .HasColumnType("int");

                    b.Property<int>("AlquilerRetail")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdFamilia")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Peso")
                        .HasColumnType("real");

                    b.Property<float>("PesoReferencia")
                        .HasColumnType("real");

                    b.HasKey("SKU");

                    b.HasIndex("IdFamilia");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Dryadas.Models.Data.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("PApellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SApellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Dryadas.Models.Data.UsuarioCliente", b =>
                {
                    b.Property<int>("IdUsuarioCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuarioCliente"));

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdUsuarioCliente");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdUsuario");

                    b.ToTable("UsuarioClientes");
                });

            modelBuilder.Entity("Dryadas.Models.Data.DetalleEvento", b =>
                {
                    b.HasOne("Dryadas.Models.Data.Evento", "Evento")
                        .WithMany("DetalleEventos")
                        .HasForeignKey("IdEvento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dryadas.Models.Data.Orden", "Orden")
                        .WithMany("DetalleEventos")
                        .HasForeignKey("IdOrden")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("Dryadas.Models.Data.DetalleOrden", b =>
                {
                    b.HasOne("Dryadas.Models.Data.Orden", "Orden")
                        .WithMany("DetallesOrdenes")
                        .HasForeignKey("IdOrden")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dryadas.Models.Data.Producto", "Producto")
                        .WithMany("DetallesOrdenes")
                        .HasForeignKey("SKU")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orden");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Dryadas.Models.Data.EstadoProductoProducto", b =>
                {
                    b.HasOne("Dryadas.Models.Data.Producto", "Producto")
                        .WithMany("EstadoProductoProductos")
                        .HasForeignKey("SKU")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dryadas.Models.Data.EstadoProducto", "EstadoProducto")
                        .WithMany("EstadoProductoProductos")
                        .HasForeignKey("idEstadoProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoProducto");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Dryadas.Models.Data.EstadosOrden", b =>
                {
                    b.HasOne("Dryadas.Models.Data.Estado", "Estado")
                        .WithMany("EstadosOrdenes")
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dryadas.Models.Data.Orden", "Orden")
                        .WithMany("EstadosOrdenes")
                        .HasForeignKey("IdOrden")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("Dryadas.Models.Data.Orden", b =>
                {
                    b.HasOne("Dryadas.Models.Data.Cliente", null)
                        .WithMany("Orden")
                        .HasForeignKey("ClienteIdCliente");

                    b.HasOne("Dryadas.Models.Data.Usuario", "Usuario")
                        .WithMany("Ordenes")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Dryadas.Models.Data.Producto", b =>
                {
                    b.HasOne("Dryadas.Models.Data.Familia", "Familia")
                        .WithMany("Productos")
                        .HasForeignKey("IdFamilia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Familia");
                });

            modelBuilder.Entity("Dryadas.Models.Data.UsuarioCliente", b =>
                {
                    b.HasOne("Dryadas.Models.Data.Cliente", "Cliente")
                        .WithMany("UsuarioClientes")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dryadas.Models.Data.Usuario", "Usuario")
                        .WithMany("UsuarioClientes")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Dryadas.Models.Data.Cliente", b =>
                {
                    b.Navigation("Orden");

                    b.Navigation("UsuarioClientes");
                });

            modelBuilder.Entity("Dryadas.Models.Data.Estado", b =>
                {
                    b.Navigation("EstadosOrdenes");
                });

            modelBuilder.Entity("Dryadas.Models.Data.EstadoProducto", b =>
                {
                    b.Navigation("EstadoProductoProductos");
                });

            modelBuilder.Entity("Dryadas.Models.Data.Evento", b =>
                {
                    b.Navigation("DetalleEventos");
                });

            modelBuilder.Entity("Dryadas.Models.Data.Familia", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Dryadas.Models.Data.Orden", b =>
                {
                    b.Navigation("DetalleEventos");

                    b.Navigation("DetallesOrdenes");

                    b.Navigation("EstadosOrdenes");
                });

            modelBuilder.Entity("Dryadas.Models.Data.Producto", b =>
                {
                    b.Navigation("DetallesOrdenes");

                    b.Navigation("EstadoProductoProductos");
                });

            modelBuilder.Entity("Dryadas.Models.Data.Usuario", b =>
                {
                    b.Navigation("Ordenes");

                    b.Navigation("UsuarioClientes");
                });
#pragma warning restore 612, 618
        }
    }
}
